version: '3.7'

services:
  api:
    container_name: event-api
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/app