version: '3.7'

services:
  api:
    container_name: event-api
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    container_name: event-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    env_file:
      - .env.example
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8583:80"
    depends_on:
      - db